Repository The-Naveen/NITCONF, pull requests merged in 2024-01, with the labels that each got.

#19 Added some more specializations.
  src/main/resources/templates/Profile.html
Labels: enhancement

#24 connected to every other page from Home.html
  src/main/resources/templates/Home.html
Labels: connected

#28 Enhancement.
  src/main/resources/templates/Profile.html
Labels: edited
